### PR TITLE
interpolation for `readFile` with `utf8`

### PR DESCRIPTION
**Pull request by tachibana-shin**

### CODE REVIEW

**Comment by jcubic** [comment]
I'm afraid this doesn't work like this right now:

```javascript
  async readFile(filepath, opts) {
    const { encoding } = opts;
    ...
  }
```

**Comment by tachibana-shin** [comment]
> I'm afraid this doesn't work like this right now:
> 
> ```js
>   async readFile(filepath, opts) {
>     const { encoding } = opts;
>     ...
>   }
> ```

fixed

**Comment by jcubic** [comment]
This is standard of nodeJS readFile to accept a string, can you maybe update the code in:
https://github.com/isomorphic-git/lightning-fs/blob/main/src/DefaultBackend.js#L97
to match your first TypeScript definition?

**Comment by tachibana-shin** [comment]
> This is standard of nodeJS readFile to accept a string, can you maybe update the code in: https://github.com/isomorphic-git/lightning-fs/blob/main/src/DefaultBackend.js#L97 to match your first TypeScript definition?

All right, I'll update it.

**Comment by tachibana-shin** [comment]
> This is standard of nodeJS readFile to accept a string, can you maybe update the code in: https://github.com/isomorphic-git/lightning-fs/blob/main/src/DefaultBackend.js#L97 to match your first TypeScript definition?

updated

**Comment by jcubic** [comment]
Thanks for the changes. It looks good.

**Pull request merged**
