### PR TITLE
Throw an error if writing a file where there is already a directory

### LINKED ISSUE #119: It is possible to write in a directory as if it was a file
`writeFile` will happily write to a path that is currently a directory. The children of the directory will be kept, but its type will become `'file'` and thus any subsequent operation will throw `ENOTDIR`.

Here is a minimal example. 

```js
import FS from "@isomorphic-git/lightning-fs";

const fs = new FS("demo");
const pfs = fs.promises;

const main = async () => {
  await pfs.mkdir("/foo");
  await pfs.writeFile("/foo", "bar");
  await pfs.readdir("/foo"); // throws ENOTDIR
};

main();
```

In Node, the following error is thrown by `writeFile`: `Uncaught [Error: EISDIR: illegal operation on a directory, open 'test']`

### PR DESCRIPTION
**Pull request by elegaanz**
Fixes #119

### CODE REVIEW

**Comment by jcubic** [comment]
LGTM, but I need to check why the check didn't run.

**Comment by elegaanz** [comment]
Apparently ubuntu 18.04 has been deprecated for Github Actions and Azure DevOps: https://github.com/actions/runner-images/issues/6002

Do you want another PR to update your CI? :smile:

**Comment by jcubic** [comment]
If you can update Ubuntu it would be great.

**Comment by jcubic** [comment]
When you're done (and your PR will be merged) you can add yourself to the isomorphic-git repo as a contributor.

**Pull request merged**
